"""Product catalogue: products, variants, images, and import records.

Revision ID: 0004
Revises: 0003
Created: 2026-07-31 19:37:14.716432+00:00

Four tables, all tenant-scoped. Every index leads with ``tenant_id`` so that a
query which forgets the tenant filter cannot use the index — the mistake shows
up as a slow query in testing rather than as silently correct-looking output.

Autogenerate also proposed rewriting unique constraints into unique indexes on
``tenants``, ``roles`` and ``refresh_tokens``. Those were removed by hand: they
are an artefact of how the earlier migrations declared those constraints, not a
change Phase 4 needs, and rewriting a constraint on a live table is not
something to do as a side effect of adding a catalogue.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("source", sa.Enum("aliexpress", "manual", name="product_source"), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("external_canonical_id", sa.String(length=128), nullable=True),
        sa.Column("external_url", sa.String(length=1024), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category_id", sa.String(length=64), nullable=True),
        sa.Column("category_name", sa.String(length=255), nullable=True),
        sa.Column("brand", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum("draft", "active", "archived", "unavailable", name="product_status"),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("cost_price_min", sa.Numeric(precision=16, scale=4), nullable=True),
        sa.Column("cost_price_max", sa.Numeric(precision=16, scale=4), nullable=True),
        sa.Column("stock_quantity", sa.Integer(), nullable=False),
        sa.Column("supplier_name", sa.String(length=255), nullable=True),
        sa.Column("supplier_id", sa.String(length=128), nullable=True),
        sa.Column("rating", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("review_count", sa.Integer(), nullable=True),
        sa.Column("order_count", sa.Integer(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_sync_error", sa.String(length=1024), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_products_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint(
            "tenant_id", "source", "external_id", name="uq_products_tenant_source_external"
        ),
    )
    op.create_index(op.f("ix_products_created_at"), "products", ["created_at"], unique=False)
    op.create_index(op.f("ix_products_deleted_at"), "products", ["deleted_at"], unique=False)
    op.create_index(
        "ix_products_tenant_category", "products", ["tenant_id", "category_id"], unique=False
    )
    op.create_index(
        "ix_products_tenant_created", "products", ["tenant_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_products_tenant_id"), "products", ["tenant_id"], unique=False)
    op.create_index("ix_products_tenant_status", "products", ["tenant_id", "status"], unique=False)
    op.create_table(
        "product_images",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_images_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_product_images_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_images")),
        sa.UniqueConstraint("product_id", "url", name="uq_images_product_url"),
    )
    op.create_index(
        "ix_images_tenant_product", "product_images", ["tenant_id", "product_id"], unique=False
    )
    op.create_index(
        op.f("ix_product_images_created_at"), "product_images", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_product_images_deleted_at"), "product_images", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_product_images_product_id"), "product_images", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_product_images_tenant_id"), "product_images", ["tenant_id"], unique=False
    )
    op.create_table(
        "product_imports",
        sa.Column("source", sa.Enum("aliexpress", "manual", name="product_source"), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "running", "succeeded", "failed", "skipped", name="import_status"),
            nullable=False,
        ),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("requested_by_user_id", sa.UUID(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.String(length=2048), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_imports_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["users.id"],
            name=op.f("fk_product_imports_requested_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_product_imports_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_imports")),
    )
    op.create_index(
        "ix_imports_tenant_created", "product_imports", ["tenant_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_imports_tenant_status", "product_imports", ["tenant_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_product_imports_created_at"), "product_imports", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_product_imports_deleted_at"), "product_imports", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_product_imports_external_id"), "product_imports", ["external_id"], unique=False
    )
    op.create_index(
        op.f("ix_product_imports_tenant_id"), "product_imports", ["tenant_id"], unique=False
    )
    op.create_table(
        "product_variants",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("external_variant_id", sa.String(length=128), nullable=False),
        sa.Column("external_attributes", sa.String(length=1024), nullable=True),
        sa.Column("label", sa.String(length=512), nullable=True),
        sa.Column("cost_price", sa.Numeric(precision=16, scale=4), nullable=True),
        sa.Column("list_price", sa.Numeric(precision=16, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("stock_quantity", sa.Integer(), nullable=False),
        sa.Column("image_url", sa.String(length=1024), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_variants_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_product_variants_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_variants")),
        sa.UniqueConstraint(
            "product_id", "external_variant_id", name="uq_variants_product_external"
        ),
    )
    op.create_index(
        op.f("ix_product_variants_created_at"), "product_variants", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_product_variants_deleted_at"), "product_variants", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_product_variants_product_id"), "product_variants", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_product_variants_tenant_id"), "product_variants", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_variants_tenant_product", "product_variants", ["tenant_id", "product_id"], unique=False
    )


def downgrade() -> None:
    op.drop_index("ix_variants_tenant_product", table_name="product_variants")
    op.drop_index(op.f("ix_product_variants_tenant_id"), table_name="product_variants")
    op.drop_index(op.f("ix_product_variants_product_id"), table_name="product_variants")
    op.drop_index(op.f("ix_product_variants_deleted_at"), table_name="product_variants")
    op.drop_index(op.f("ix_product_variants_created_at"), table_name="product_variants")
    op.drop_table("product_variants")
    op.drop_index(op.f("ix_product_imports_tenant_id"), table_name="product_imports")
    op.drop_index(op.f("ix_product_imports_external_id"), table_name="product_imports")
    op.drop_index(op.f("ix_product_imports_deleted_at"), table_name="product_imports")
    op.drop_index(op.f("ix_product_imports_created_at"), table_name="product_imports")
    op.drop_index("ix_imports_tenant_status", table_name="product_imports")
    op.drop_index("ix_imports_tenant_created", table_name="product_imports")
    op.drop_table("product_imports")
    op.drop_index(op.f("ix_product_images_tenant_id"), table_name="product_images")
    op.drop_index(op.f("ix_product_images_product_id"), table_name="product_images")
    op.drop_index(op.f("ix_product_images_deleted_at"), table_name="product_images")
    op.drop_index(op.f("ix_product_images_created_at"), table_name="product_images")
    op.drop_index("ix_images_tenant_product", table_name="product_images")
    op.drop_table("product_images")
    op.drop_index("ix_products_tenant_status", table_name="products")
    op.drop_index(op.f("ix_products_tenant_id"), table_name="products")
    op.drop_index("ix_products_tenant_created", table_name="products")
    op.drop_index("ix_products_tenant_category", table_name="products")
    op.drop_index(op.f("ix_products_deleted_at"), table_name="products")
    op.drop_index(op.f("ix_products_created_at"), table_name="products")
    op.drop_table("products")

    # Postgres enum types outlive the tables that use them. Without these drops
    # the downgrade "succeeds" and the next upgrade fails with
    # "type product_source already exists" — a broken downgrade that only
    # reveals itself on the way back up, which is the worst time to find it.
    sa.Enum(name="import_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="product_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="product_source").drop(op.get_bind(), checkfirst=True)
