"""Order management: orders, items, shipments, tracking, timeline, sync runs.

Revision ID: 0005
Revises: 0004
Created: 2026-07-31 21:14:52.038947+00:00

Six tables, all tenant-scoped, mirroring the catalogue's conventions: every
index leads with ``tenant_id``, money is ``Numeric(16, 4)``, and idempotent
sync is enforced by the ``(tenant_id, source, external_id)`` unique constraint
on ``orders`` rather than by call-site checks.

Autogenerate again proposed rewriting unique constraints into unique indexes on
``tenants``, ``roles`` and ``refresh_tokens`` — the same artefact removed by
hand from migration 0004, for the same reason: it is a consequence of how the
early migrations declared those constraints, not a change this phase needs.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("source", sa.Enum("aliexpress", "manual", name="order_source"), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("external_status", sa.String(length=128), nullable=True),
        sa.Column(
            "fulfillment_status",
            sa.Enum(
                "pending",
                "awaiting_payment",
                "paid",
                "processing",
                "fulfilled",
                "shipped",
                "delivered",
                "cancelled",
                "refunded",
                "disputed",
                name="fulfillment_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "payment_status",
            sa.Enum("unknown", "unpaid", "paid", "refunded", name="order_payment_status"),
            nullable=False,
        ),
        sa.Column("buyer_name", sa.String(length=255), nullable=True),
        sa.Column("buyer_country", sa.String(length=2), nullable=True),
        sa.Column("recipient_name", sa.String(length=255), nullable=True),
        sa.Column("recipient_phone", sa.String(length=64), nullable=True),
        sa.Column("address_line1", sa.String(length=512), nullable=True),
        sa.Column("address_line2", sa.String(length=512), nullable=True),
        sa.Column("city", sa.String(length=128), nullable=True),
        sa.Column("province", sa.String(length=128), nullable=True),
        sa.Column("postal_code", sa.String(length=32), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("total_amount", sa.Numeric(precision=16, scale=4), nullable=True),
        sa.Column("shipping_amount", sa.Numeric(precision=16, scale=4), nullable=True),
        sa.Column("external_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_sync_error", sa.String(length=1024), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_orders_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint(
            "tenant_id", "source", "external_id", name="uq_orders_tenant_source_external"
        ),
    )
    op.create_index(op.f("ix_orders_created_at"), "orders", ["created_at"], unique=False)
    op.create_index(op.f("ix_orders_deleted_at"), "orders", ["deleted_at"], unique=False)
    op.create_index(
        "ix_orders_tenant_external_created",
        "orders",
        ["tenant_id", "external_created_at"],
        unique=False,
    )
    op.create_index(
        "ix_orders_tenant_fulfillment", "orders", ["tenant_id", "fulfillment_status"], unique=False
    )
    op.create_index(op.f("ix_orders_tenant_id"), "orders", ["tenant_id"], unique=False)
    op.create_table(
        "order_events",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "created", "status_change", "synced", "shipment", "webhook", name="order_event_type"
            ),
            nullable=False,
        ),
        sa.Column("from_status", sa.String(length=64), nullable=True),
        sa.Column("to_status", sa.String(length=64), nullable=True),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_events_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_order_events_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_events")),
    )
    op.create_index(
        op.f("ix_order_events_created_at"), "order_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_order_events_deleted_at"), "order_events", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_order_events_tenant_id"), "order_events", ["tenant_id"], unique=False)
    op.create_index(
        "ix_order_events_tenant_order", "order_events", ["tenant_id", "order_id"], unique=False
    )
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("external_item_id", sa.String(length=128), nullable=True),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("external_product_id", sa.String(length=128), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("sku_attributes", sa.String(length=512), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=16, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("external_status", sa.String(length=128), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_items_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_order_items_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_order_items_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
    )
    op.create_index(op.f("ix_order_items_created_at"), "order_items", ["created_at"], unique=False)
    op.create_index(op.f("ix_order_items_deleted_at"), "order_items", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_order_items_tenant_id"), "order_items", ["tenant_id"], unique=False)
    op.create_index(
        "ix_order_items_tenant_order", "order_items", ["tenant_id", "order_id"], unique=False
    )
    op.create_table(
        "order_sync_runs",
        sa.Column(
            "trigger",
            sa.Enum("manual", "scheduled", "webhook", name="order_sync_trigger"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("running", "succeeded", "failed", "partial", name="order_sync_status"),
            nullable=False,
        ),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("orders_seen", sa.Integer(), nullable=False),
        sa.Column("orders_created", sa.Integer(), nullable=False),
        sa.Column("orders_updated", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.String(length=2048), nullable=True),
        sa.Column("requested_by_user_id", sa.UUID(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["users.id"],
            name=op.f("fk_order_sync_runs_requested_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_order_sync_runs_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_sync_runs")),
    )
    op.create_index(
        op.f("ix_order_sync_runs_created_at"), "order_sync_runs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_order_sync_runs_deleted_at"), "order_sync_runs", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_order_sync_runs_tenant_id"), "order_sync_runs", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_order_sync_runs_tenant_started",
        "order_sync_runs",
        ["tenant_id", "started_at"],
        unique=False,
    )
    op.create_table(
        "shipments",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("tracking_number", sa.String(length=128), nullable=True),
        sa.Column("carrier", sa.String(length=128), nullable=True),
        sa.Column("service_name", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "in_transit",
                "out_for_delivery",
                "delivered",
                "exception",
                "unknown",
                name="shipment_status",
            ),
            nullable=False,
        ),
        sa.Column("estimated_delivery_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_location", sa.String(length=255), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_shipments_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_shipments_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipments")),
    )
    op.create_index(op.f("ix_shipments_created_at"), "shipments", ["created_at"], unique=False)
    op.create_index(op.f("ix_shipments_deleted_at"), "shipments", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_shipments_tenant_id"), "shipments", ["tenant_id"], unique=False)
    op.create_index(
        "ix_shipments_tenant_order", "shipments", ["tenant_id", "order_id"], unique=False
    )
    op.create_index(
        "ix_shipments_tenant_tracking", "shipments", ["tenant_id", "tracking_number"], unique=False
    )
    op.create_table(
        "tracking_events",
        sa.Column("shipment_id", sa.UUID(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=128), nullable=True),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipments.id"],
            name=op.f("fk_tracking_events_shipment_id_shipments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_tracking_events_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tracking_events")),
    )
    op.create_index(
        op.f("ix_tracking_events_created_at"), "tracking_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_tracking_events_deleted_at"), "tracking_events", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_tracking_events_tenant_id"), "tracking_events", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_tracking_events_tenant_shipment",
        "tracking_events",
        ["tenant_id", "shipment_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tracking_events_tenant_shipment", table_name="tracking_events")
    op.drop_index(op.f("ix_tracking_events_tenant_id"), table_name="tracking_events")
    op.drop_index(op.f("ix_tracking_events_deleted_at"), table_name="tracking_events")
    op.drop_index(op.f("ix_tracking_events_created_at"), table_name="tracking_events")
    op.drop_table("tracking_events")
    op.drop_index("ix_shipments_tenant_tracking", table_name="shipments")
    op.drop_index("ix_shipments_tenant_order", table_name="shipments")
    op.drop_index(op.f("ix_shipments_tenant_id"), table_name="shipments")
    op.drop_index(op.f("ix_shipments_deleted_at"), table_name="shipments")
    op.drop_index(op.f("ix_shipments_created_at"), table_name="shipments")
    op.drop_table("shipments")
    op.drop_index("ix_order_sync_runs_tenant_started", table_name="order_sync_runs")
    op.drop_index(op.f("ix_order_sync_runs_tenant_id"), table_name="order_sync_runs")
    op.drop_index(op.f("ix_order_sync_runs_deleted_at"), table_name="order_sync_runs")
    op.drop_index(op.f("ix_order_sync_runs_created_at"), table_name="order_sync_runs")
    op.drop_table("order_sync_runs")
    op.drop_index("ix_order_items_tenant_order", table_name="order_items")
    op.drop_index(op.f("ix_order_items_tenant_id"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_deleted_at"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_created_at"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index("ix_order_events_tenant_order", table_name="order_events")
    op.drop_index(op.f("ix_order_events_tenant_id"), table_name="order_events")
    op.drop_index(op.f("ix_order_events_deleted_at"), table_name="order_events")
    op.drop_index(op.f("ix_order_events_created_at"), table_name="order_events")
    op.drop_table("order_events")
    op.drop_index(op.f("ix_orders_tenant_id"), table_name="orders")
    op.drop_index("ix_orders_tenant_fulfillment", table_name="orders")
    op.drop_index("ix_orders_tenant_external_created", table_name="orders")
    op.drop_index(op.f("ix_orders_deleted_at"), table_name="orders")
    op.drop_index(op.f("ix_orders_created_at"), table_name="orders")
    op.drop_table("orders")

    # Native enum types are not dropped with their tables; without these the
    # next upgrade fails on "type already exists".
    sa.Enum(name="shipment_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="order_sync_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="order_sync_trigger").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="order_event_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="order_payment_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="fulfillment_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="order_source").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
